#!/bin/bash

python object_detection/model_main.py \
    --alsologtostderr \
    --pipeline_config_path="ssdlite_mobilenet_v2_coco.config" \
    --model_dir="/tmp/"

python object_detection/export_inference_graph.py \
    --input_type=image_tensor \
    --pipeline_config_path="ssdlite_mobilenet_v2_coco.config" \
    --trained_checkpoint_prefix="/tmp/model.ckpt"
    --output_directory="/opt/ml/model"